// <auto-generated />
using DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataLayer.Migrations.GeoServiceTest
{
    [DbContext(typeof(GeoServiceTestContext))]
    [Migration("20201229205000_initGeoTestService")]
    partial class initGeoTestService
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("DataLayer.BaseClasses.CountryRiver", b =>
                {
                    b.Property<string>("CountryName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RiverName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CountryName", "RiverName");

                    b.HasIndex("RiverName");

                    b.ToTable("CountryRiver");
                });

            modelBuilder.Entity("DataLayer.BaseClasses.DCity", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DCountryName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DCountryName1")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("Population")
                        .HasColumnType("bigint");

                    b.HasKey("Name");

                    b.HasIndex("DCountryName");

                    b.HasIndex("DCountryName1");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("DataLayer.BaseClasses.DContinent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Population")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("Id");

                    b.ToTable("Continents");
                });

            modelBuilder.Entity("DataLayer.BaseClasses.DCountry", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("ContinentId")
                        .HasColumnType("bigint");

                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("Population")
                        .HasColumnType("bigint");

                    b.Property<float>("Surface")
                        .HasColumnType("real");

                    b.HasKey("Name");

                    b.HasIndex("ContinentId");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("DataLayer.BaseClasses.DRiver", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<double>("Length")
                        .HasColumnType("float");

                    b.HasKey("Name");

                    b.ToTable("Rivers");
                });

            modelBuilder.Entity("DataLayer.BaseClasses.CountryRiver", b =>
                {
                    b.HasOne("DataLayer.BaseClasses.DCountry", "Country")
                        .WithMany("Rivers")
                        .HasForeignKey("CountryName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataLayer.BaseClasses.DRiver", "River")
                        .WithMany("Countries")
                        .HasForeignKey("RiverName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("River");
                });

            modelBuilder.Entity("DataLayer.BaseClasses.DCity", b =>
                {
                    b.HasOne("DataLayer.BaseClasses.DCountry", null)
                        .WithMany("Capitals")
                        .HasForeignKey("DCountryName");

                    b.HasOne("DataLayer.BaseClasses.DCountry", null)
                        .WithMany("Cities")
                        .HasForeignKey("DCountryName1");
                });

            modelBuilder.Entity("DataLayer.BaseClasses.DCountry", b =>
                {
                    b.HasOne("DataLayer.BaseClasses.DContinent", "Continent")
                        .WithMany("Countries")
                        .HasForeignKey("ContinentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Continent");
                });

            modelBuilder.Entity("DataLayer.BaseClasses.DContinent", b =>
                {
                    b.Navigation("Countries");
                });

            modelBuilder.Entity("DataLayer.BaseClasses.DCountry", b =>
                {
                    b.Navigation("Capitals");

                    b.Navigation("Cities");

                    b.Navigation("Rivers");
                });

            modelBuilder.Entity("DataLayer.BaseClasses.DRiver", b =>
                {
                    b.Navigation("Countries");
                });
#pragma warning restore 612, 618
        }
    }
}
