// <auto-generated />
using System;
using DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataLayer.Migrations.GeoServiceTest
{
    [DbContext(typeof(GeoServiceTestContext))]
    partial class GeoServiceTestContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("DataLayer.BaseClasses.CountryRiver", b =>
                {
                    b.Property<int>("CountryKey")
                        .HasColumnType("int");

                    b.Property<int>("RiverKey")
                        .HasColumnType("int");

                    b.HasKey("CountryKey", "RiverKey");

                    b.HasIndex("RiverKey");

                    b.ToTable("CountryRiver");
                });

            modelBuilder.Entity("DataLayer.BaseClasses.DCity", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("DCountryKey")
                        .HasColumnType("int");

                    b.Property<int?>("DCountryKey1")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Population")
                        .HasColumnType("bigint");

                    b.HasKey("Key");

                    b.HasIndex("DCountryKey");

                    b.HasIndex("DCountryKey1");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("DataLayer.BaseClasses.DContinent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Population")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("Id");

                    b.ToTable("Continents");
                });

            modelBuilder.Entity("DataLayer.BaseClasses.DCountry", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("ContinentId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Population")
                        .HasColumnType("bigint");

                    b.Property<float>("Surface")
                        .HasColumnType("real");

                    b.HasKey("Key");

                    b.HasIndex("ContinentId");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("DataLayer.BaseClasses.DRiver", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<double>("Length")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("Rivers");
                });

            modelBuilder.Entity("DataLayer.BaseClasses.CountryRiver", b =>
                {
                    b.HasOne("DataLayer.BaseClasses.DCountry", "Country")
                        .WithMany("Rivers")
                        .HasForeignKey("CountryKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataLayer.BaseClasses.DRiver", "River")
                        .WithMany("Countries")
                        .HasForeignKey("RiverKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("River");
                });

            modelBuilder.Entity("DataLayer.BaseClasses.DCity", b =>
                {
                    b.HasOne("DataLayer.BaseClasses.DCountry", null)
                        .WithMany("Capitals")
                        .HasForeignKey("DCountryKey");

                    b.HasOne("DataLayer.BaseClasses.DCountry", null)
                        .WithMany("Cities")
                        .HasForeignKey("DCountryKey1");
                });

            modelBuilder.Entity("DataLayer.BaseClasses.DCountry", b =>
                {
                    b.HasOne("DataLayer.BaseClasses.DContinent", "Continent")
                        .WithMany("Countries")
                        .HasForeignKey("ContinentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Continent");
                });

            modelBuilder.Entity("DataLayer.BaseClasses.DContinent", b =>
                {
                    b.Navigation("Countries");
                });

            modelBuilder.Entity("DataLayer.BaseClasses.DCountry", b =>
                {
                    b.Navigation("Capitals");

                    b.Navigation("Cities");

                    b.Navigation("Rivers");
                });

            modelBuilder.Entity("DataLayer.BaseClasses.DRiver", b =>
                {
                    b.Navigation("Countries");
                });
#pragma warning restore 612, 618
        }
    }
}
